In [ ]:
data="Merhaba"
data[0]

'M'

In [ ]:
data[-1]

'a'

In [ ]:
len(data)

7

In [ ]:
a,b,c=1,2,-10

In [ ]:
print(a,b,c)

1 2 -10


In [ ]:
notum=90

if notum>90:
  print("AA")
elif notum>80:
  print("BA")
else:
  print("Kaldiniz")

BA


In [ ]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
i=0
while i<10:
  print(i)
  i=i+1

0
1
2
3
4
5
6
7
8
9


TUPLE, LİSTE,SÖZLÜK

In [ ]:
a=(10,20,3.14)

In [ ]:
a

(10, 20, 3.14)

In [ ]:
a[1]

20

In [ ]:
a[5]

IndexError: tuple index out of range

In [ ]:
a[1]=100 #tuple degistirilemez

TypeError: 'tuple' object does not support item assignment

In [ ]:
a.append(100) # ekleme olmaz

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
liste=[10,100,3.14,"erzurum",True]

In [ ]:
liste

[10, 100, 3.14, 'erzurum', True]

In [ ]:
liste[1]

100

In [ ]:
liste[1]=-50

In [ ]:
liste

[10, -50, 3.14, 'erzurum', True]

In [ ]:
liste.append(1000)

In [ ]:
liste

[10, -50, 3.14, 'erzurum', True, 1000]

In [ ]:
sozluk={"erzurum":25, "ankara":6, "trabzon":61}

In [ ]:
print("Erzurum plakasi %d " % sozluk['erzurum'])

Erzurum plakasi 25 


In [ ]:
sozluk["trabzon"]

61

In [ ]:
sozluk["trabzon"]=100

In [ ]:
sozluk

{'erzurum': 25, 'ankara': 6, 'trabzon': 100}

In [ ]:
sozluk.keys()

dict_keys(['erzurum', 'ankara', 'trabzon'])

In [ ]:
sozluk.values()

dict_values([25, 6, 100])

In [ ]:
for i in sozluk.keys():
  print(i)

erzurum
ankara
trabzon


In [ ]:
for i in sozluk.keys():
  print(sozluk[i])

25
6
100


In [ ]:
def toplam(a,b,):
  return a+b
toplam(10,20)

30

In [ ]:
def fonksiyon():
  x=(1,2,3,4)
  return x
a,b,c,d=fonksiyon()
print(a,b,c,d)

1 2 3 4


In [ ]:
a=5
x=a**2
print(x)

25


In [ ]:
toplam1=lambda x:x**2
print(toplam1(5))

25


In [ ]:
liste= [1,2,3]
y=map(lambda x:x**2,liste)
print(list(y))

[1, 4, 9]


In [ ]:
liste1= [1,2,3,4]
liste2=[4,5,6,10]

x=zip(liste1,liste2) # zip paralel gruplamayi saglar..
deger=list(x)

print(deger)

[(1, 4), (2, 5), (3, 6), (4, 10)]


In [ ]:
list(zip(*deger))

[(1, 2, 3, 4), (4, 5, 6, 10)]

#NUMPY

In [ ]:
import numpy as np

In [ ]:
array =np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [ ]:
array.shape # shape satir sutun eleman sayisini verir.

(15,)

In [ ]:
a=array.reshape(3,5) # reshape yeniden boyutlandirma yapar.
a # total eleman sayisinin istedigimiz orana tam bolunmesi gerekiyor yoksa hata verir.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
a.shape

(3, 5)

In [ ]:
a.ndim # ndim dizinin boyut sayisini verir.

2

In [ ]:
a.dtype.name

'int64'

In [ ]:
a.size # Total eleman sayisini verir.

15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
array1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
sifir =np.zeros((3,4))

In [ ]:
sifir

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
sifir[0,0]=100
sifir

array([[100.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [ ]:
birler=np.ones((3,4))

In [ ]:
birler

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a= np.arange(10,100,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
a=np.arange(1,45)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [ ]:
a=np.linspace(10,100,20) # 10 dan 100e kadar 20 esit parcaya boler.
a

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

In [ ]:
a=np.linspace(10,100,19)
a

array([ 10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,  60.,
        65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

a+b

array([5, 7, 9])

In [ ]:
a-b

array([-3, -3, -3])

In [ ]:
a**2

array([1, 4, 9])

In [ ]:
b=np.sin(a)
b

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
b<0.6

array([False, False,  True])

In [ ]:
a=np.random.random((5,5)) # 0 la 1 arasinda random sayi olusturur.
a

array([[0.05274904, 0.72108489, 0.70031136, 0.71131299, 0.92612916],
       [0.00548004, 0.76777613, 0.24890483, 0.39335486, 0.61053636],
       [0.39616345, 0.6487291 , 0.43747361, 0.67264411, 0.21861831],
       [0.64797137, 0.75878304, 0.2086307 , 0.48793763, 0.27286202],
       [0.79772906, 0.64805635, 0.79807971, 0.43649559, 0.94727962]])

In [ ]:
a=np.random.randn(5) # +- sonsuz arasi sayi uretir.
a

array([-0.87850976, -0.30959054,  1.48376854, -2.01081778, -1.57373346])

In [ ]:
a=np.array([[1,4],[2,5],[3,6]])
a

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
b=np.transpose(a)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.random.random((5,5))
a

array([[0.61020706, 0.8383994 , 0.06890413, 0.4789893 , 0.00428352],
       [0.91082271, 0.27827403, 0.68875744, 0.04414986, 0.06572694],
       [0.20638925, 0.95441393, 0.49151104, 0.49038508, 0.62697259],
       [0.37498223, 0.86933432, 0.5744883 , 0.66774868, 0.92852166],
       [0.25870917, 0.35962908, 0.11293179, 0.32620668, 0.84525306]])

In [ ]:
toplam=np.sum(a)
toplam

np.float64(12.075991210735035)

In [ ]:
maximum=np.max(a)
maximum

np.float64(0.9544139268351065)

In [ ]:
a

array([[0.61020706, 0.8383994 , 0.06890413, 0.4789893 , 0.00428352],
       [0.91082271, 0.27827403, 0.68875744, 0.04414986, 0.06572694],
       [0.20638925, 0.95441393, 0.49151104, 0.49038508, 0.62697259],
       [0.37498223, 0.86933432, 0.5744883 , 0.66774868, 0.92852166],
       [0.25870917, 0.35962908, 0.11293179, 0.32620668, 0.84525306]])

In [ ]:
a.sum(axis=0) #sutun numpy icin

array([2.36111041, 3.30005075, 1.9365927 , 2.00747959, 2.47075776])

In [ ]:
a.sum(axis=1)#satir numpy icin

array([2.0007834 , 1.98773098, 2.76967188, 3.41507518, 1.90272977])

In [ ]:
np.sqrt(a)

array([[0.78115751, 0.91564152, 0.26249596, 0.69209053, 0.0654486 ],
       [0.95437032, 0.52751685, 0.82991412, 0.21011869, 0.25637265],
       [0.45430083, 0.97694111, 0.70107848, 0.700275  , 0.79181601],
       [0.61235792, 0.93238099, 0.75795006, 0.81715891, 0.96359829],
       [0.50863461, 0.59969082, 0.33605326, 0.57114506, 0.91937645]])

In [ ]:
a=np.array([1,2,9])
b=np.array([4,5,6])
c=np.concatenate([a,b])
c

array([1, 2, 9, 4, 5, 6])

In [ ]:
c[2:]

array([9, 4, 5, 6])

In [ ]:
c[::]

array([1, 2, 9, 4, 5, 6])

In [ ]:
c[::-1]

array([6, 5, 4, 9, 2, 1])